Employee Manager/Controllers/AccessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmployeeManager.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.Filters;
using MySql.Data.MySqlClient;

namespace EmployeeManager.Controllers
{
    public class SecurityController : Controller
    {
        public string accessToken = "";
        public int loggedinEmployee = 0;
        public bool EmployeeIsAdmin = false;
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {

            Database.AccessQueries AccessQuery = new Database.AccessQueries();
            AccessModel Access = new AccessModel();

            Access.LoginToken = HttpContext.Session.GetString("AccessToken");
            Access.Username = HttpContext.Session.GetString("Username");
            accessToken = Access.LoginToken;

            Access = AccessQuery.VerifyTokenData(Access, Access.Username, Access.LoginToken);

            if (Access.LoggedIn == false)
            {
                if (!filterContext.Controller.ToString().Contains("AccessController"))
                {
                    Response.Redirect("Access/");
                }

            }
            else
            {
                EmployeeIsAdmin = Access.IsAdmin;
                loggedinEmployee = Access.EmployeeId;
               // Response.Redirect("Home/");
            }
           

        }
    }
    public class AccessController : SecurityController
    {
        public AccessModel SessionAccess = new AccessModel();
        private Database.AccessQueries AccessQuery = new Database.AccessQueries();

        public IActionResult Index(AccessModel AccessToken)
        {
         
            if (!string.IsNullOrEmpty(AccessToken.Username)) {

                AccessToken = VerifyAccess(AccessToken);

                if (AccessToken.LoggedIn)
                {
                    AccessQuery.UpdateToken(AccessToken);

                    HttpContext.Session.SetString("AccessToken", AccessToken.LoginToken);
                    HttpContext.Session.SetString("Username", AccessToken.Username);

                    return Redirect("~/Home/");

                } else
                {
                   return  Redirect("~/Access/");

                }
 
            }

            ViewData["Message"] = "Please log in to continue.";
            return View();


        }

        public IActionResult Logout()
        {
            HttpContext.Session.SetString("AccessToken", "");
            HttpContext.Session.SetString("Username", "");

                    return Redirect("~/Access/");
 
        }

  
        private AccessModel VerifyAccess(AccessModel AccessToken)
        {
           
            AccessToken = AccessQuery.getLoginData(AccessToken);

            if (AccessToken.LoggedIn)
            {
                AccessToken.LoggedInTimestamp = DateTime.Now;
                AccessToken.LoginToken = GenerateToken();
            } else
            {
                AccessToken.LoggedInTimestamp = DateTime.MinValue;
                AccessToken.LoginToken = "";
            }
            return AccessToken;
        }

        public string GenerateToken()
        {
           
            var allChar = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            var random = new Random();
            var resultToken = new string(
               Enumerable.Repeat(allChar, 8)
               .Select(token => token[random.Next(token.Length)]).ToArray());

            string authToken = resultToken.ToString();


            return authToken;
        }


        

    }
}

Employee Manager/Views/Shared/Close.cshtml
@{
    ViewData["Title"] = "Close";
}

<h2>Close</h2>

<script>
    window.close();
</script>

Employee Manager/Views/Shared/_ActiveTasks.cshtml
@model IEnumerable<EmployeeManager.Models.QueueRollModel>
@{
    ViewData["Title"] = "Active Tasks";
    ViewData["Message"] = "Below is your active tasks, Click stop task to stop the task.";
}


<style>

    #listtable {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

        #listtable td, #listtable th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #listtable tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        #listtable tr:hover {
            background-color: #ddd;
        }

        #listtable th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #4CAF50;
            color: white;
        }


    input[type=text], select {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }



    .button {
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: inherit;
    }

    .button2 { /* Blue */
        background-color: #008CBA;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: inherit;
    }

    .button3 { /* Red */
        background-color: red;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: inherit;
    }

    div {
        border-radius: 5px;
    }
</style>
<script type="text/javascript">



    ShowAdd = function () {

        var child = window.open('/Queue/Add', "Add Queue", 'width=780px,height=380px,top=0,left=250');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }


    ShowEdit = function (QueueId) {

        var child = window.open('/Queue/Edit?id=' + QueueId, "Edit Queue", 'width=780px,height=380px,top=0,left=250');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }



    StopItem = function (RollId) {


        var child = window.open('/QueueRoll/StopQueue?id=' + RollId, "Stop Queued Task", 'width=100px,height=100px,top=150,left=150');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }

    DeleteQueueRoll = function (RollId) {

        var child = window.open('/QueueRoll/Delete?id=' + RollId, "Delete Queued task", 'width=100px,height=100px,top=125,left=250');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }


</script>


<table width="100%">
    <tr>
        <td>
            <h3>@ViewData["Title"]</h3>
            <strong>@ViewData["Message"]</strong><br />
            <small>When you stop a task it gets placed back in the queue to continue on later.</small>
        </td>
        <td align="right"></td>
    </tr>
</table>
<hr />
<table width="100%" border="0" id="listtable">
    <tr>
        <th>Task Description</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {

    @if (item.StopDate == DateTime.MinValue)
        {
    <tr id="row_@item.TaskId">
        <td>
            <Strong>@item.Task.Title</Strong><br />
            @item.Task.Description<br />
            <small>Task ID: @item.Task.TaskId</small> - 
            <small>Employee: @item.Employee.Fullname</small>
        </td>


        <td>
            <input type="button" class="button2" id="btnsto_@item.RollId" name="btnsto_@item.RollId" value="Stop Task" onclick="StopItem(@item.RollId);" />
        </td>
    </tr>
        }


    }

</table>

Employee Manager/Views/Shared/_AvailableTasks.cshtml
@model IEnumerable<EmployeeManager.Models.QueueModel>
@{
    ViewData["Title"] = "Task Queue";
    ViewData["Message"] = "Below is the tasks available for you, Click start task to begin the task.";
}

<style>

    #listtable {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

        #listtable td, #listtable th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #listtable tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        #listtable tr:hover {
            background-color: #ddd;
        }

        #listtable th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #4CAF50;
            color: white;
        }


    input[type=text], select {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }



    .button {
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: inherit;
    }

    .button2 { /* Blue */
        background-color: #008CBA;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: inherit;
    }

    .button3 { /* Red */
        background-color: #f44336;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: inherit;
    }

    div {
        border-radius: 5px;
    }
</style>
<script type="text/javascript">



    ShowAdd = function () {

        var child = window.open('/Queue/Add', "Add Task to Queue", 'width=780px,height=380px,top=150,left=250');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }


    ShowEdit = function (QueueId) {

        var child = window.open('/Queue/Edit?id=' + QueueId, "Edit Queued Task", 'width=780px,height=380px,top=150,left=250');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }

    StartQueue = function (QueueId) {

        var child = window.open('/Queue/StartQueue?id=' + QueueId, "Start Queue", 'width=100px,height=100px,top=150,left=150');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }

    DeleteQueue = function (QueueId) {

        var child = window.open('/Queue/Delete?id=' + QueueId, "Edit Employee", 'width=100px,height=100px,top=125,left=250');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }



</script>


<table width="100%">
    <tr>
        <td>
            <h3>@ViewData["Title"]</h3>
            <strong>@ViewData["Message"]</strong>
            <small>When you stop a task it will be available moved to the active queue.</small>
        </td>
        <td align="right"></td>
    </tr>
</table>
<hr />
<table width="100%" border="0" id="listtable">
    <tr>
        <th>Task Description</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {


    <tr id="row_@item.TaskId">
        <td>
            <Strong>@item.Task.Title</Strong><br />
            @item.Task.Description<br />
            <small>Task ID: @item.Task.TaskId</small> - 
            <small>Employee: @item.Employee.Fullname</small>
        </td>

        <td>
            <input type="button" Class="button" id="btnsta_@item.QueueId" name="btnsta_@item.QueueId" value="Start Task" onclick="StartQueue(@item.QueueId);" />

        </td>
    </tr>
    }

</table>

Employee Manager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee Manager</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
       
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Employee Manager</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Access" asp-action="Logout">Logout</a></li>


                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Employee Manager</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>