Employee Manager/Controllers/QueueController.cs
using EmployeeManager.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System;
using System.Collections.Generic;

namespace EmployeeManager.Controllers
{
 
    public class QueueController : SecurityController
    {
        private Database.QueueQueries QueueQuery = new Database.QueueQueries();
        private Database.QueueRollQueries QueueRollQuery = new Database.QueueRollQueries();
        private Database.EmployeeQueries EmployeeQuery = new Database.EmployeeQueries();
        private Database.TaskQueries TaskQuery = new Database.TaskQueries();


        public IActionResult Index()
        {
            if (EmployeeIsAdmin == false) { return Redirect("~/Queue/Close"); }
            ViewData["Message"] = "Please Select an Queue to edit, or add a new Queue.";

            List<QueueModel> QueueList = new List<QueueModel>();
            List<EmployeeModel> EmployeeList = new List<EmployeeModel>();
            List<TaskModel> TaskList = new List<TaskModel>();

            EmployeeList = EmployeeQuery.GetEmployees();
            TaskList = TaskQuery.GetTasks();
            QueueList = QueueQuery.GetQueues(QueueList, loggedinEmployee, EmployeeIsAdmin);

            foreach (QueueModel QueueItem in QueueList)
            {
                QueueItem.Employee = EmployeeList.Find(x => x.EmployeeId.Equals(QueueItem.EmployeeId));

                QueueItem.Task = TaskList.Find(x => x.TaskId.Equals(QueueItem.TaskId));
            }


            return View(QueueList);

        }

        public IActionResult List()
        {
            if (EmployeeIsAdmin == false) { return Redirect("~/Queue/Close"); }
            ViewData["Message"] = "Please Select an Queue to edit, or add a new Queue.";

            List<QueueModel> QueueList = new List<QueueModel>();
            List<EmployeeModel> EmployeeList = new List<EmployeeModel>();
            List<TaskModel> TaskList = new List<TaskModel>();

            EmployeeList = EmployeeQuery.GetEmployees();
            TaskList = TaskQuery.GetTasks();
            QueueList = QueueQuery.GetQueuesJoinedRoll(QueueList, loggedinEmployee, EmployeeIsAdmin);

            foreach (QueueModel QueueItem in QueueList)
            {
                QueueItem.Employee = EmployeeList.Find(x => x.EmployeeId.Equals(QueueItem.EmployeeId));

                QueueItem.Task = TaskList.Find(x => x.TaskId.Equals(QueueItem.TaskId));
            }


            return PartialView("_List", QueueList);

        }
        public IActionResult Close()
        {

            return View();

        }

        public IActionResult Delete(int id)
        {
            QueueQuery.DeleteQueue(id);

            return Redirect("~/Queue/Close");
        }
        public IActionResult Add()
        {
            if (EmployeeIsAdmin == false) { return Redirect("~/Queue/Close"); }
            ViewData["Message"] = "Please enter the Queue information.";

            QueueModel Queue = new QueueModel();
            Database.EmployeeQueries EmployeeQuery = new Database.EmployeeQueries();
            Database.TaskQueries TaskQuery = new Database.TaskQueries();
            Queue.Employees = EmployeeQuery.GetEmployees();
            Queue.Tasks = TaskQuery.GetTasks();


            return PartialView("_Add", Queue);

        }

        public IActionResult Start(int id)
        {

            ViewData["Message"] = "Please enter the Queue information.";
            QueueModel Queue = new QueueModel
            {
                QueueId = id,
                Employees = EmployeeQuery.GetEmployees(),
                Tasks = TaskQuery.GetTasks()
            };


            return PartialView("_Start", Queue);

        }

        public IActionResult StartQueue(int id)
        {
            QueueRollModel QueueRoll = new QueueRollModel();
            EmployeeModel Employee = new EmployeeModel();
            QueueModel Queue = new QueueModel();
            TaskModel Task = new TaskModel();


            
            Queue = QueueQuery.GetQueue(id);

            Employee = EmployeeQuery.GetEmployee(Queue.EmployeeId);
            Task = TaskQuery.GetTask(Queue.TaskId);

            QueueRoll.QueueId = Queue.QueueId;
            QueueRoll.EmployeeId = Queue.EmployeeId;
            QueueRoll.TaskId = Queue.TaskId;
            QueueRoll.StartDate = DateTime.Now;
            Task.StartDate = QueueRoll.StartDate;
            QueueRoll.Rate = Employee.Rate;

            Task.Status = "Started";
            Task = TaskQuery.UpdateTask(Task);

            QueueRoll = QueueRollQuery.CreateQueueRoll(QueueRoll);

    

          return Redirect("~/Queue/Close");


        }

        public IActionResult CompleteQueue(int id)
        {
            QueueModel Queue = new QueueModel();
            EmployeeModel Employee = new EmployeeModel();
            TaskModel Task = new TaskModel();

            Queue = QueueQuery.GetQueue(id);

            Employee = EmployeeQuery.GetEmployee(Queue.EmployeeId);
            Task = TaskQuery.GetTask(Queue.TaskId);

            Task.Completed = 1;
            Task.DateCompleted = DateTime.Now;

            QueueQuery.UpdateQueueComplete(Queue.QueueId);
            TaskQuery.UpdateTaskComplete(Task);

            // return Redirect("~/Queue/Close");
            return PartialView("Close");

        }
        public IActionResult AddQueue(QueueModel Queue)
        {
            if (EmployeeIsAdmin == false) { return Redirect("~/Queue/Close"); }
            ViewData["Message"] = "Please enter the Queue information.";

            Queue = QueueQuery.CreateQueue(Queue);

            return Redirect("~/Queue/Close");


        }
        public IActionResult Edit(int id)
        {
            if (EmployeeIsAdmin == false) { return Redirect("~/Queue/Close"); }
            ViewData["Message"] = "Please edit the Queue information.";

            QueueModel Queue = new QueueModel
            {
                QueueId = id,
                Employees = EmployeeQuery.GetEmployees(),
                Tasks = TaskQuery.GetTasks()
            };

     
            Queue = QueueQuery.GetQueue(Queue);


            ViewData["TaskID"] = "Queue ID: " + Queue.QueueId;
          

            return PartialView("_Edit", Queue);
            

        }

        public IActionResult EditQueue(QueueModel Queue)
        {
            if (EmployeeIsAdmin == false) { return Redirect("~/Queue/Close"); }
            Queue = QueueQuery.UpdateQueue(Queue);

            return Redirect("~/Queue/Close");

        }

    }
}

Employee Manager/Controllers/QueueRollController.cs
using EmployeeManager.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System;
using System.Collections.Generic;

namespace EmployeeManager.Controllers
{
   
    public class QueueRollController : SecurityController
    {
        private Database.QueueQueries QueueQuery = new Database.QueueQueries();
        private Database.QueueRollQueries QueueRollQuery = new Database.QueueRollQueries();
        private Database.EmployeeQueries EmployeeQuery = new Database.EmployeeQueries();
        private Database.TaskQueries TaskQuery = new Database.TaskQueries();

        public IActionResult Index()
        {

            ViewData["Message"] = "Please Select a QueueRoll to edit, or add a new QueueRoll.";

            List<QueueRollModel> QueueRollList = new List<QueueRollModel>();
            List<EmployeeModel> EmployeeList = new List<EmployeeModel>();
            List<TaskModel> TaskList = new List<TaskModel>();
            EmployeeList = EmployeeQuery.GetEmployees();
            TaskList = TaskQuery.GetTasks();

            QueueRollList = QueueRollQuery.GetQueuesRoll(QueueRollList, loggedinEmployee, EmployeeIsAdmin);

           // TaskList.Find.First(x => x.Id == idArray).materialId

            foreach (QueueRollModel QueueRollItem in QueueRollList)
            {
                QueueRollItem.Employee = EmployeeList.Find(x => x.EmployeeId.Equals(QueueRollItem.EmployeeId));

                QueueRollItem.Task = TaskList.Find(x => x.TaskId.Equals(QueueRollItem.TaskId));
            }


            return View(QueueRollList);

        }
        public IActionResult List()
        {

            ViewData["Message"] = "Please Select a QueueRoll to edit, or add a new QueueRoll.";

            List<QueueRollModel> QueueRollList = new List<QueueRollModel>();
            List<EmployeeModel> EmployeeList = new List<EmployeeModel>();
            List<TaskModel> TaskList = new List<TaskModel>();
            EmployeeList = EmployeeQuery.GetEmployees();
            TaskList = TaskQuery.GetTasks();

            QueueRollList = QueueRollQuery.GetQueuesRoll(QueueRollList, loggedinEmployee, EmployeeIsAdmin);

            // TaskList.Find.First(x => x.Id == idArray).materialId

            foreach (QueueRollModel QueueRollItem in QueueRollList)
            {
                QueueRollItem.Employee = EmployeeList.Find(x => x.EmployeeId.Equals(QueueRollItem.EmployeeId));

                QueueRollItem.Task = TaskList.Find(x => x.TaskId.Equals(QueueRollItem.TaskId));
            }


            
            return PartialView("_List", QueueRollList);

        }


        public IActionResult Close()
        {

            return View();

        }

        public IActionResult StopQueue(int id)
        {
            QueueRollModel QueueRoll = new QueueRollModel();
            EmployeeModel Employee = new EmployeeModel();

            QueueRoll = QueueRollQuery.GetQueueRoll(id);

            Employee = QueueRoll.Employee;

            QueueRoll.StopDate = DateTime.Now;

            QueueRoll.Minutes = GetMinutes(QueueRoll.StartDate, QueueRoll.StopDate);
            QueueRoll.Rate = Employee.Rate;

            QueueRoll = QueueRollQuery.UpdateQueueRollStop(QueueRoll);

            return PartialView("Close", QueueRoll);
           // return Redirect("~/QueueRoll/Index");


        }

    


        public IActionResult Add()
        {

            ViewData["Message"] = "Please enter the QueueRoll information.";

            QueueRollModel QueueRoll = new QueueRollModel();
           
            return PartialView("_Add", QueueRoll);

        }

        public double GetMinutes(DateTime startdate, DateTime stopdate)
        {

            TimeSpan span = stopdate.Subtract(startdate);

            double totalminutes = span.TotalMinutes;

            return totalminutes;

        }

        public IActionResult AddQueueRoll(QueueRollModel QueueRoll)
        {

            ViewData["Message"] = "Please enter the QueueRoll information.";

            QueueRoll = QueueRollQuery.CreateQueueRoll(QueueRoll);

           // return Redirect("~/Employee/Add");
            return Redirect("~/QueueRoll/Close");


        }
        public IActionResult Edit(int id)
        {
            ViewData["Message"] = "Please edit the QueueRoll information.";

            QueueRollModel QueueRoll = new QueueRollModel
            {
                RollId = id
            };

     
            QueueRoll = QueueRollQuery.GetQueueRoll(QueueRoll);


            ViewData["TaskID"] = "QueueRoll ID: " + QueueRoll.RollId;
          

            return PartialView("_Edit", QueueRoll);
            

        }

        public IActionResult Delete(int id)
        {
            QueueRollQuery.DeleteQueueRoll(id);

            return Redirect("~/QueueRoll/Close");
        }

        public IActionResult EditQueueRoll(QueueRollModel QueueRoll)
        {

            QueueRoll = QueueRollQuery.UpdateQueueRoll(QueueRoll);

            return Redirect("~/QueueRoll/Close");

        }

    }
}

Employee Manager/Views/QueueRoll/Close.cshtml
@{
    ViewData["Title"] = "Close";
}

<h2>Close</h2>

<script>
    window.close();
</script>

Employee Manager/Views/QueueRoll/Index.cshtml
@model IEnumerable<EmployeeManager.Models.QueueRollModel>
@{
    ViewData["Title"] = "Login";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<script type="text/javascript">



    ShowAdd = function () {
        
        var child = window.open('/Queue/Add', "Add Queue", 'width=780px,height=600px,top=0,left=250');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }


    ShowEdit = function (QueueId) {
       
        var child = window.open('/Queue/Edit?id=' + QueueId, "Edit Queue", 'width=780px,height=600px,top=0,left=250');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }

 

    StopItem = function (RollId) {
        $.post("QueueRoll/StopQueue", { id: RollId }, function (data) {
            $("#row_" + RollId).hide();
        });
    }

</script>

<input type="button" id="btn_AddNew" value="Add Queue" onclick="ShowAdd();" />
<hr />

<table width="100%" border="1" class="table">
    <tr>
        <th>Queue ID</th>
        <th>Assigned Employee</th>
        <th>Task</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {

        @if (item.StopDate == DateTime.MinValue)
        {
            <tr id="row_@item.RollId">
                <td>
                    @item.RollId
                </td>
                <td>
                    @item.QueueId
                </td>
                <td>
                    <strong>@item.Employee.Name @item.Employee.Lastname</strong>
                </td>
                <td>
                    (@item.Task.TaskId) <strong>@item.Task.Title</strong> <br />
                    @item.Task.Description
                </td>

                <td>
                    <input type="button" id="btnsto_@item.RollId" name="btnsto_@item.RollId" value="Stop Task" onclick="StopItem(@item.RollId);" />
                    @*<input type="button" id="btn_@item.RollId" value="Edit Queue" onclick="ShowEdit(@item.RollId);" />*@
                </td>
            </tr>
        }


    }

</table>

Employee Manager/Views/QueueRoll/_Add.cshtml
@model EmployeeManager.Models.QueueRollModel
@{
    ViewData["Title"] = "Add Queue";
}




<style>
    input[type=text], select {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

    div {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
    }
</style>

<table width="100%">
    <tr>
        <td>
            <h3>@ViewData["Title"]</h3>
            <strong>@ViewData["Message"]</strong>
        </td>
        <td></td>
    </tr>
</table>
<hr />

@using (Html.BeginForm("AddQueue", "Queue", FormMethod.Post))
{
<table width="100%" cellpadding="2" cellspacing="3">
    <tr>
        <td colspan="2">
            <strong>Employee</strong><br />
 
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <strong>Task</strong><br />
          
        </td>
    </tr>
    
</table>

    <p>
        <input type="submit" name="Submit" value="Save Task to Queue">
    </p>

}

Employee Manager/Views/QueueRoll/_Edit.cshtml
@model EmployeeManager.Models.QueueRollModel
@{
    ViewData["Title"] = "Edit Queue";
}


<style>
    input[type=text], select {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

    div {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
    }
</style>
<script type="text/javascript">
    $(function () {
        $(".date-picker").datepicker({
            dateFormat: 'dd-M-yy'
        });

    });

</script>
<table width="100%">
    <tr>
        <td>
            <h2>@ViewData["Title"]</h2>
            <h3>@ViewData["Message"]</h3>
        </td>
        <td></td>
    </tr>
</table>
<hr />
@using (Html.BeginForm("EditQueue", "Queue", FormMethod.Post))
{
    @Html.HiddenFor(m => m.QueueId);
    <table width="100%" cellpadding="2" cellspacing="3">
        <tr>
            <td colspan="2">
                <strong>Employee</strong><br />

            </td>
        </tr>
        <tr>
            <td colspan="2">
                <strong>Task</strong><br />

            </td>
        </tr>


    </table>

    <p>
        <input type="submit" name="Submit" value="Save Queued Task">
    </p>

}

Employee Manager/Views/QueueRoll/_List.cshtml
@model IEnumerable<EmployeeManager.Models.QueueRollModel>
@{
    ViewData["Title"] = "Manage Active Tasks";
}


<style>

    #listtable {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

        #listtable td, #listtable th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #listtable tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        #listtable tr:hover {
            background-color: #ddd;
        }

        #listtable th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #4CAF50;
            color: white;
        }


    input[type=text], select {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }



    .button {
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: inherit;
    }

    .button2 { /* Blue */
        background-color: #008CBA;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: inherit;
    }

    .button3 { /* Red */
        background-color: red;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: inherit;
    }

    .button4 { /* Orange */
        background-color: darkorange;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: inherit;
    }
    div {
        border-radius: 5px;
    }
</style>
<script type="text/javascript">



    ShowAdd = function () {
        
        var child = window.open('/Queue/Add', "Add Queue", 'width=780px,height=380px,top=0,left=250');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }


    ShowEdit = function (QueueId) {
        
        var child = window.open('/Queue/Edit?id=' + QueueId, "Edit Queue", 'width=780px,height=380px,top=0,left=250');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }



    StopItem = function (RollId) {
    
        
        var child = window.open('/QueueRoll/StopQueue?id=' + RollId, "Stop Queued Task", 'width=100px,height=100px,top=150,left=150');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }



    DeleteQueueRoll = function (RollId) {

        var child = window.open('/QueueRoll/Delete?id=' + RollId, "Delete Queued task", 'width=100px,height=100px,top=125,left=250');
        var timer = setInterval(checkChild, 500);

        function checkChild() {
            if (child.closed) {
                window.location.reload(true);
                clearInterval(timer);
            }
        }
    }


</script>


<table width="100%">
    <tr>
        <td>
            <h3>@ViewData["Title"]</h3>
            <strong>@ViewData["Message"]</strong>
        </td>
        <td align="right"></td>
    </tr>
</table>
<hr />
<table width="100%" border="0" id="listtable">
    <tr>
        <th>Roll ID</th>
        <th>Queue ID</th>
        <th>Assigned Employee</th>
        <th>Task</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {

        @if (item.StopDate == DateTime.MinValue)
        {
            <tr id="row_@item.RollId">
                <td>
                    @item.RollId
                </td>
                <td>
                    @item.QueueId
                </td>
                <td>
                    <strong>@item.Employee.Fullname</strong>
                </td>
                <td>
                    (@item.Task.TaskId) <strong>@item.Task.Title</strong> <br />
                    @item.Task.Description
                </td>

                <td>
                    <input type="button" class="button2" id="btnsto_@item.RollId" name="btnsto_@item.RollId" value="Stop Task" onclick="StopItem(@item.RollId);" />


                    <input type="button" class="button3" id="btn_@item.RollId" value="Delete Active Task" onclick="DeleteQueueRoll(@item.RollId);" />

                </td>
            </tr>
        }


    }

</table>

Employee Manager/Views/QueueRoll/_Stop.cshtml
@model EmployeeManager.Models.QueueModel
@{
    ViewData["Title"] = "Edit Queue";
}
<table width="100%">
    <tr>
        <td>
            <h2>@ViewData["Title"]</h2>
            <h3>@ViewData["Message"]</h3>
        </td>
        <td><div align="right"><img src="file:///C|/Users/jvrso/Desktop/Buttons/Group%201.png" width="64" height="64"></div></td>
    </tr>
</table>
<hr />
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

<style>
    input[type=text], select {
        width: 100%;
        padding: 12px 20px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 100%;
        background-color: #4CAF50;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

    div {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
    }
</style>
<script type="text/javascript">
    $(function () {
        $(".date-picker").datepicker({
            dateFormat: 'dd-M-yy'
        });

    });

</script>

@using (Html.BeginForm("EditQueue", "Queue", FormMethod.Post))
{
    @Html.HiddenFor(m => m.QueueId);
<table width="100%" cellpadding="2" cellspacing="3">
    <tr>
        <td colspan="2">
            <strong>Employee</strong><br />
            @Html.DropDownListFor(m => m.EmployeeId, new SelectList(Model.Employees, "EmployeeId", "Name", Model.EmployeeId))
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <strong>Task</strong><br />
            @Html.DropDownListFor(m => m.TaskId, new SelectList(Model.Tasks, "TaskId", "Title", Model.TaskId))
        </td>
    </tr>


</table>

    <p>
        <input type="submit" name="Submit" value="Save Queue">
    </p>

}